logging:
  level:
    root: WARN
    org.springframework: INFO
    org.pantasoft.pantastore: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: pantastore
    description: v1

server:
  servlet:
    context-path: /app

spring:
  messages:
    basename: lang/messages

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
