logging:
  level:
    root: WARN
    org.springframework: INFO
    org.pantasoft.pantastore: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: pantastore
    description: v1

server:
  servlet:
    context-path: /app

spring:
  messages:
    basename: lang/messages

  datasource:
    url: jdbc:h2:mem:pantadb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database: H2
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: pantadb
        ddl-auto: validate
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    contexts: dev
    defaultSchema: pantadb
    enabled: true
    liquibaseSchema: public
